### ISSUE TITLE
future = tasks.async (future, loop=self)

### ISSUE THREAD

**Issue by lhasxl** [LilZevi/Amino-Tools#3]
Traceback (most recent call last) :
![472466B9-BA8B-44FA-999A-742311223927](https://user-images.githubusercontent.com/89989512/144084440-e61f9552-cfdd-4b3f-acd3-c13e23d3f027.jpeg)

"/opt/virtualenvs/python3/lib/python3.8/
site-packages/asyncio/base_events.py"
', line 296
future = tasks.async (future, loop=self)
SyntaxError: invalid syntax
I’m using replit

**Comment by vraestoren** [comment]
сука иди нахуй заебал
