### ISSUE TITLE
Cant run on windows

### ISSUE THREAD

**Issue by Kuro-dev** [LilZevi/Amino-Tools#5]
I followed the instructions and installed the requirements via pip. 

I know the instructions were for linux OS, but do you know of a possible way to get this to run on win 10?

`Traceback (most recent call last):
  File "C:\Users\Kuro\Desktop\test\Amino-Tools\Amino-Tools.py", line 3, in <module>
    from amino_tools_configs import main_functions
  File "C:\Users\Kuro\Desktop\test\Amino-Tools\amino_tools_configs\main_functions.py", line 1, in <module>
    import amino
  File "C:\Python310\lib\site-packages\amino\__init__.py", line 9, in <module>
    from .sub_client import SubClient
  File "C:\Python310\lib\site-packages\amino\sub_client.py", line 12, in <module>
    from json_minify import json_minify
ModuleNotFoundError: No module named 'json_minify'
`

**Comment by vraestoren** [comment]
pip install json_minify

**Comment by Kuro-dev** [comment]
@deluvsushi 
so i came back from my vacation and tried your fix. now i got this: 

> $ python Amino-Tools.py
> Traceback (most recent call last):
>   File "C:\Users\Kuro\Desktop\test\Amino-Tools\Amino-Tools.py", line 4, in <module>
>     print(f"""{fg(36)}
>   File "C:\Python310\lib\encodings\cp1252.py", line 19, in encode
>     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
> UnicodeEncodeError: 'charmap' codec can't encode characters in position 74-115: character maps to undefined

**Comment by vraestoren** [comment]
reinstall code
