### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by Kuro-dev** [LilZevi/Amino-Tools#7]
`{'api:statuscode': 218, 'api:duration': '0.001s', 'api:message': 'Error! Your device is currently not supported, or the app is out of date. Please update to the latest version.', 'api:timestamp': '2023-03-27T08:57:52Z'}`

Could it be that the device specified in device.json is outdated? or the Amino client?

Or maybe i did something wrong idk

**Comment by vraestoren** [comment]
lazy to give normal answer
